# Generated by Django 3.1.7 on 2021-03-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='to_do', max_length=100, verbose_name='Durum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='Başlık', max_length=100, verbose_name='Başlık'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=4000, verbose_name='Açıklama'),
        ),
    ]
