# Generated by Django 3.1.7 on 2021-03-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20210327_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'managed': True, 'verbose_name': 'Görev', 'verbose_name_plural': 'Görevler'},
        ),
    ]
